### ISSUE TITLE
[BUG] Empty data message is "No columns selected"

### ISSUE THREAD

**Issue by woozyking** [EQWorks/extended-semantic-components#43]
**Component Name**
`DataTable`

**Describe the bug**
When data is empty, the table would render `No columns selected` as the placeholder message.

**To Reproduce**
Props that are passed into the component:
```
data = []

<DataTable data={data} />
```

**Expected behavior**
A more descriptive message, such as "Empty data".

**Screenshots**
![图片](https://user-images.githubusercontent.com/2837532/54447912-e9e2ef00-4720-11e9-9f1c-22394dccff1f.png)

**Environment (please complete the following information):**
 - OS: macOS Mojave
 - Browser: firefox
 - Version: 2.3.2
 - React Version: 16.8

**Comment by Goondrious** [comment]
message is `No Results Found :(`, or whatever the empty search message is, when you specify columns

**Comment by woozyking** [comment]
In zero-config context
